@Tutorial12_HostAddress = http://localhost:5228

### Get trips 
GET {{Tutorial12_HostAddress}}/api/trips
Accept: application/json

### Get trips (page 2 and 5 items per page)
GET {{Tutorial12_HostAddress}}/api/trips?page=2&pageSize=5
Accept: application/json

### Register a new client (John) to a trip (204 No Content)
POST {{Tutorial12_HostAddress}}/api/trips/1/clients
Content-Type: application/json

{
  "FirstName": "John",
  "LastName": "Doe",
  "Email": "john.doe@example.com",
  "Telephone": "+48 123 456 789",
  "Pesel":  "75820293919",
  "PaymentDate": "2025-07-01"
}

### Register a new client (Mark) to a trip (204 No Content)
POST {{Tutorial12_HostAddress}}/api/trips/1/clients
Content-Type: application/json

{
  "FirstName": "Mark",
  "LastName": "Mohn",
  "Email": "mark.mohn@example.com",
  "Telephone": "+48 542 243 423",
  "Pesel":  "51876472831",
  "PaymentDate": "2025-07-02"
}


### Register the same client again to the same trip (400 Bad Request)
POST {{Tutorial12_HostAddress}}/api/trips/2/clients
Content-Type: application/json

{
  "FirstName": "John",
  "LastName": "Doe",
  "Email": "john.doe@example.com",
  "Telephone": "+48 123 456 789",
  "Pesel":  "75820293919",
  "PaymentDate": "2025-07-01"
}


### Delete a client
DELETE {{Tutorial12_HostAddress}}/api/clients/2
Accept: application/json

### Delete a client (404 Not Found)
DELETE {{Tutorial12_HostAddress}}/api/clients/123
Accept: application/json
